
spring:
  application:
    name: outworld-elasticsearch

  rabbitmq:
    host: 101.133.149.79
    username: admin
    password: admin
    port: 5672
server:
  port: 8002

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka